apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sd
  annotations:
    github.com/project-slug: carlosbioingeniero/dsdsd   
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
